CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY ,
    login TEXT NOT NULL ,
    password TEXT NOT NULL
);
CREATE TABLE booking (
    id INT AUTO_INCREMENT PRIMARY KEY ,
    time INT NOT NULL,
    id_micro INT REFERENCES microwave(id) ON UPDATE CASCADE ON DELETE CASCADE,
    id_user INT REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
 );
CREATE TABLE microwave(
    id INT AUTO_INCREMENT PRIMARY KEY ,
    floors INT NOT NULL
)
